using System.Runtime.CompilerServices;
using Microsoft.Build.Framework;
using Mono.Cecil;

[assembly: InternalsVisibleTo("IgnoresAccessChecksToGenerator.Tasks.Test")]

#nullable disable

namespace IgnoresAccessChecksToGenerator.Tasks
{
    public class PublicizeInternals : Microsoft.Build.Utilities.Task
    {
        private readonly AssemblyResolver _resolver = new AssemblyResolver();

        [Required]
        public ITaskItem[] SourceReferences { get; set; }

        [Required]
        public ITaskItem[] AssemblyNames { get; set; }

        [Required]
        public string IntermediateOutputPath { get; set; }

        [Required]
        public string GeneratedCodeFilePath { get; set; }

        public ITaskItem[] ExcludeTypeNames { get; set; }

        public bool OmitAttributeDefinition { get; set; }

        public override bool Execute()
        {
            if (SourceReferences == null) throw new ArgumentNullException(nameof(SourceReferences));

            var assemblyNames = new HashSet<string>(AssemblyNames.Select(t => t.ItemSpec), StringComparer.OrdinalIgnoreCase);

            if (assemblyNames.Count == 0)
            {
                return true;
            }

            var excludedTypeNames = new TypeExclusions();
            if (ExcludeTypeNames != null)
            {
                foreach (var item in ExcludeTypeNames)
                {
                    excludedTypeNames.Add(item.ItemSpec, item.GetMetadata("Assembly"));
                }
            }

            var targetPath = IntermediateOutputPath;
            Directory.CreateDirectory(targetPath);

            GenerateAttributes(targetPath, assemblyNames, OmitAttributeDefinition);

            foreach (var assemblyPath in SourceReferences
                .Select(a => Path.GetDirectoryName(GetFullFilePath(targetPath, a.ItemSpec))))
            {
                _resolver.AddSearchDirectory(assemblyPath);
            }

            foreach (var assembly in SourceReferences)
            {
                var assemblyPath = GetFullFilePath(targetPath, assembly.ItemSpec);
                var assemblyName = Path.GetFileNameWithoutExtension(assemblyPath);
                if (assemblyNames.Contains(assemblyName))
                {
                    var targetAssemblyPath = Path.Combine(targetPath, Path.GetFileName(assemblyPath));

                    CreatePublicAssembly(assemblyName, assemblyPath, targetAssemblyPath, excludedTypeNames);
                    Log.LogMessageFromText("Created publicized assembly at " + targetAssemblyPath, MessageImportance.Normal);
                }
            }

            return true;
        }

        private void GenerateAttributes(string path, IEnumerable<string> assemblyNames, bool omitAttributeDefinition)
        {
            var content = BuildAttributeFileContent(assemblyNames, omitAttributeDefinition);
            File.WriteAllText(GeneratedCodeFilePath, content, System.Text.Encoding.UTF8);

            Log.LogMessageFromText("Generated IgnoresAccessChecksTo attributes", MessageImportance.Low);
        }

        internal static string BuildAttributeFileContent(IEnumerable<string> assemblyNames, bool omitAttributeDefinition)
        {
            var attributes = string.Join(Environment.NewLine,
                assemblyNames.Select(a => $@"[assembly: System.Runtime.CompilerServices.IgnoresAccessChecksTo(""{a}"")]"));

            var attributeDefinition = omitAttributeDefinition ? "" : """

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
    internal sealed class IgnoresAccessChecksToAttribute : Attribute
    {
        public IgnoresAccessChecksToAttribute(string assemblyName)
        {
        }
    }
}
""";

            var content = $$"""
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

{{attributes}}
{{attributeDefinition}}
""";
            return content.TrimEnd() + Environment.NewLine;
        }

        private void CreatePublicAssembly(string assemblyName, string source, string target, TypeExclusions excludedTypeNames)
        {
            var assembly = AssemblyDefinition.ReadAssembly(source,
                new ReaderParameters { AssemblyResolver = _resolver });

            foreach (var module in assembly.Modules)
            {
                foreach (var type in module.GetTypes().Where(type => !excludedTypeNames.IsExcluded(assemblyName, type.FullName)))
                {
                    if (!type.IsNested && type.IsNotPublic)
                    {
                        type.IsPublic = true;
                    }
                    else if (type.IsNestedAssembly ||
                             type.IsNestedFamilyOrAssembly ||
                             type.IsNestedFamilyAndAssembly)
                    {
                        type.IsNestedPublic = true;
                    }

                    foreach (var field in type.Fields)
                    {
                        if (field.IsAssembly ||
                            field.IsFamilyOrAssembly ||
                            field.IsFamilyAndAssembly)
                        {
                            field.IsPublic = true;
                        }
                    }

                    foreach (var method in type.Methods)
                    {
                        if (method.IsAssembly ||
                            method.IsFamilyOrAssembly ||
                            method.IsFamilyAndAssembly)
                        {
                            method.IsPublic = true;
                        }
                    }
                }
            }

            assembly.Write(target);
            // copy XML docs alongside the new assembly
            var xmlSource = Path.ChangeExtension(source, ".xml");
            if (File.Exists(xmlSource))
            {
                var xmlTarget = Path.ChangeExtension(target, ".xml");
                File.Copy(xmlSource, xmlTarget, overwrite: true);
                Log.LogMessageFromText($"Copied XML docs to {xmlTarget}", MessageImportance.Low);
            }
        }

        private string GetFullFilePath(string basePath, string path) =>
            Path.IsPathRooted(path) ? Path.GetFullPath(path) : Path.Combine(basePath, path);

        internal sealed class TypeExclusions
        {
            private readonly HashSet<string> _global = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            private readonly Dictionary<string, HashSet<string>> _perAssembly = new Dictionary<string, HashSet<string>>(StringComparer.OrdinalIgnoreCase);

            public void Add(string typeName, string assemblyName)
            {
                if (string.IsNullOrEmpty(typeName))
                {
                    return;
                }

                if (string.IsNullOrEmpty(assemblyName))
                {
                    _global.Add(typeName);
                }
                else
                {
                    if (!_perAssembly.TryGetValue(assemblyName, out var set))
                    {
                        set = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                        _perAssembly[assemblyName] = set;
                    }

                    set.Add(typeName);
                }
            }

            public bool IsExcluded(string assemblyName, string typeFullName)
            {
                return _global.Contains(typeFullName) ||
                       (_perAssembly.TryGetValue(assemblyName, out var set) && set.Contains(typeFullName));
            }
        }

        private class AssemblyResolver : IAssemblyResolver
        {
            private readonly HashSet<string> _directories = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

            public void AddSearchDirectory(string directory)
            {
                _directories.Add(directory);
            }

            public AssemblyDefinition Resolve(AssemblyNameReference name)
            {
                return Resolve(name, new ReaderParameters());
            }

            public AssemblyDefinition Resolve(AssemblyNameReference name, ReaderParameters parameters)
            {
                var assembly = SearchDirectory(name, _directories, parameters);
                if (assembly != null)
                {
                    return assembly;
                }

                throw new AssemblyResolutionException(name);
            }

            public void Dispose()
            {
            }

            private AssemblyDefinition SearchDirectory(AssemblyNameReference name, IEnumerable<string> directories, ReaderParameters parameters)
            {
                var extensions = name.IsWindowsRuntime ? new[] { ".winmd", ".dll" } : new[] { ".exe", ".dll" };
                foreach (var directory in directories)
                {
                    foreach (var extension in extensions)
                    {
                        var file = Path.Combine(directory, name.Name + extension);
                        if (!File.Exists(file))
                            continue;
                        try
                        {
                            return GetAssembly(file, parameters);
                        }
                        catch (BadImageFormatException)
                        {
                        }
                    }
                }

                return null;
            }

            private AssemblyDefinition GetAssembly(string file, ReaderParameters parameters)
            {
                if (parameters.AssemblyResolver == null)
                    parameters.AssemblyResolver = this;

                return ModuleDefinition.ReadModule(file, parameters).Assembly;
            }
        }
    }
}